apiVersion: networking.gke.io/v1beta1
kind: MultiClusterService
metadata:
  name: frontend-multi-cluster-service
  namespace: bank-of-anthos
spec:
  template:
    spec:
      selector:
        asm: ingressgateway
      ports:
      - name: frontend
        protocol: TCP
        port: 80 # servicePort defined in MultiClusterIngress
        targetPort: 8080 # port on the asm-ingressgateway Pod that requests gets sent to (container port)
  clusters:
  - link: "northamerica-northeast1/na-ne1"
  - link: "northamerica-northeast2/na-ne2"
